apiVersion: apps/v1
kind: Deployment
metadata:
  name: seon-deployment
  namespace: default
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: test-network
  template:
    metadata:
      labels:
        app: test-network
