apiVersion: v1
kind: Service
metadata:
  name: seon-test
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  type: NodePort
  ports:
  - port: 8088
    targetPort: 80
    protocol: TCP
  selector:
    app: seon-test
